title: Jegan Kunniya's musings
author: Jegan Kunniya
email: jegan.kunniya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thanks for stopping by. I am sure some of my work have made you to be here. I would try not to disappoint you and please let me know through issues channel otherwise.
  I plan to bring in my learnings as periodic documentation/blogs.
  Thank you for reading thus far.

# social links
twitter_username: JeganKunniya # DO NOT include the @ character, or else the build will fail!
github_username:  JeganKunniya # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima